baseURL: "/"
languageCode: es-es 
title: ACME Servicios técnicos
theme: basico
author: 
  facebook: "https://es-es.facebook.com/cpilosenlaces/" 
  twitter: "https://twitter.com/cpilosenlaces" 
  email: "centro@cpilosenlaces.com" 
  name: "ACME Servicios Técnicos" 
  location: Zaragoza
  phone: (999) 999-9999 
  hours: "**Lunes-Viernes** 9:00AM - 6:00PM" 

menu:
  main: 
    - identifier: Sobre nosotros 
      name: Sobre nosotros
      url: /acercade 
      pageRef: acercade
      weight: 100 
    - identifier: contacto 
      name: Contacto 
      url: /contacto 
      pageRef: contacto
      weight: 100 
    - identifier: Curriculum
      name: Curriculum
      url: /curriculum
      pageRef: curriculum
      weight: 200 
    - identifier: blog
      name: Blog
      url: /blog
      weight: 5 
      pageRef: blog
    - identifier: viajes
      name: Viajes
      url: /viajes
      weight: 5 
      pageRef: viajes
    - identifier: peliculas
      name: Peliculas
      url: /peliculas/mas-valoradas
      weight: 5 
      pageRef: peliculas
    - identifier: tv
      name: Canales
      url: /television/canales
      weight: 50 
      pageRef: tv
    - identifier: centros
      name: Centros educativos
      url: /centros
      weight: 50 
      pageRef: centros

params: 
  color: "#4f46e5"
  copyright: "Copyright &copy; 2022 Acme Corporation. Todos los derechos reservados."
  footer:
  - title: Sobre nosotros
    content: >
      Acme Corporation es una empresa basada en la comunicación
      y en la informatica que aboga por el bien del progreso informatico. 
      Esto no es mas que una prueba sobre la realización de una web. 


  - title: Publicaciones recientes
    recents: blog
    recentCount: 7

  - title: Contact Us
    contact: true
